"""set defaul value for orders.status

Revision ID: deec34b7f7a0
Revises: 84f831d01f7f
Create Date: 2022-09-03 13:53:04.078326

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "deec34b7f7a0"
down_revision = "84f831d01f7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
