"""init migrations

Revision ID: ccf25101f9a6
Revises:
Create Date: 2022-09-03 12:36:23.030653

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccf25101f9a6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("product_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("second_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("position", sa.String(length=10), nullable=True),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "chef",
        sa.Column("chef_id", sa.Integer(), nullable=False),
        sa.Column("busy", sa.Boolean(), nullable=True),
        sa.Column("number_of_orders", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chef_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("chef_id"),
    )
    op.create_table(
        "client",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("chef_id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chef_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "supplier",
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("busy", sa.Boolean(), nullable=True),
        sa.Column("number_of_orders", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("supplier_id"),
    )
    op.create_table(
        "order_details",
        sa.Column("order_details_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("order_details_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_details")
    op.drop_table("supplier")
    op.drop_table("orders")
    op.drop_table("client")
    op.drop_table("chef")
    op.drop_table("users")
    op.drop_table("products")
    # ### end Alembic commands ###
