"""addcolumn price

Revision ID: 84f831d01f7f
Revises: ccf25101f9a6
Create Date: 2022-09-03 13:29:36.430040

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84f831d01f7f"
down_revision = "ccf25101f9a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("price", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "price")
    # ### end Alembic commands ###
