"""add column order.price

Revision ID: a384e2ed6e0e
Revises: deec34b7f7a0
Create Date: 2022-09-03 17:03:19.246857

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a384e2ed6e0e"
down_revision = "deec34b7f7a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("price", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "price")
    # ### end Alembic commands ###
