"""update order_details

Revision ID: a04f3c7ad1d9
Revises: a384e2ed6e0e
Create Date: 2022-09-09 18:34:23.590262

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a04f3c7ad1d9"
down_revision = "a384e2ed6e0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
